baseURL = "/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
languageCode = "en-US"
metaDataFormat = "yaml"
theme = "hugo-theme-learn"
themesdir = "../.."
title = "Hugo Learn Documentation"
[Languages.en]
languageName = "English"
title = "Documentation for Hugo Learn Theme"
weight = 1
[[Languages.en.menu.shortcuts]]
identifier = "ds"
name = "<i class='fab fa-fw fa-github'></i> Github repo"
url = "https://github.com/matcornic/hugo-theme-learn"
weight = 10
[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> Showcases"
url = "showcase"
weight = 11
[[Languages.en.menu.shortcuts]]
identifier = "hugodoc"
name = "<i class='fas fa-fw fa-bookmark'></i> Hugo Documentation"
url = "https://gohugo.io/"
weight = 20
[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30
[Languages.fr]
languageName = "Français"
title = "Documentation du thème Hugo Learn"
weight = 2
[[Languages.fr.menu.shortcuts]]
identifier = "ds"
name = "<i class='fab fa-fw fa-github'></i> Repo Github"
url = "https://github.com/matcornic/hugo-theme-learn"
weight = 10
[[Languages.fr.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> Vitrine"
url = "/showcase"
weight = 11
[[Languages.fr.menu.shortcuts]]
identifier = "hugodoc"
name = "<i class='fas fa-fw fa-bookmark'></i> Documentation Hugo"
url = "https://gohugo.io/"
weight = 20
[[Languages.fr.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Crédits"
url = "/credits"
weight = 30
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Doug Frayer"
description = "Documentation for Hugo Learn Theme"
disableBreadcrumb = true
disableNextPrev = true
editURL = "https://github.com/dfrayer/pdnotes/content/"
showVisitedLinks = true
